# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qd3d8UsiSw66MuUUefgopua1nrxptzEX

**Grupo 5:**
- Renzo Franco
- Harold Inca
- Luis Calderon
- Marcia Carrera
"""

url = 'https://raw.githubusercontent.com/pshiguihara/AWS_Proyecto_Prueba/master/PY01.csv'
import pandas as pd
datos = pd.read_csv(url)
print(datos)

"""1. Seleccionar los N clientes que más compran

"""

N = int(input())
d = datos.sort_values('monto', ascending=False)
print(d.head(N))

"""2. Seleccionar los N clientes con más descuentos"""

N = float(input("Numero: "))
d = (datos['descuento']>N)
print(datos[d])

"""5. Burcador Universal"""

def buscado_universal(año,mes,día):
  año = (input('Año: '))
  mes = (input('Mes: '))
  día = (input('Día: '))
  fecha = año + '' + mes + '' + día
  x = data['fecNacimiento']==fecha

#El monto de la menor venta de ese día
dt = datos.sort_values('monto', ascending=True)
for dt in range(día):
  print(día)