# -*- coding: utf-8 -*-
"""Trabajo01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Je3II-G-dJyO6h3_NPy4aqA2Qvt6n-w
"""

from graphviz import Graph

#1 y 2
pais = []
N = int(input("Numero de paises: "))
for i in range(N):
  nombre_pais = input()
  pais.append(nombre_pais)
print(pais)


#3
vecinos = []
n = int(input("Numero de vecinos: "))
for j in range(N):
  for i in range(0,n):
    nombre_vecino = input()

vecinos.append(nombre_vecino)
print(vecinos)

#4
pais_o = []
origen = input("Pais de origen: ")

pais_d = []
destino = input("Pais de destino: ")

#5
g = Graph()
cont = 0
x = 1
for i in vecinos:
  for j in vecinos[i]:
    pintarred = i + j